<a href="https://colab.research.google.com/github/DipaliDhonnar/python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a=np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


In [ ]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [ ]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
one=np.ones((3,4))
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
same_space=np.linspace(1,10,5)
same_space

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

random.array


In [ ]:
#randome variable for normalization this value range in  between 0 to 1
np.random.rand(10)

array([0.18036961, 0.8543686 , 0.93091844, 0.01661155, 0.92996223,
       0.76222407, 0.01540884, 0.95232525, 0.40381749, 0.22180007])

In [ ]:
# random variable for standardization this value range in between -3 to 3
np.random.randn(10)

array([-0.89788153, -0.95807036,  0.5389381 ,  1.15079152, -0.7622622 ,
       -0.14663078,  0.82452169,  0.68661696, -0.66787686,  0.42636396])

In [ ]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array.shape

(3, 3)

In [ ]:
array.dtype

dtype('int64')

In [ ]:
array.size

9

In [ ]:
array.max()

np.int64(9)

In [ ]:
array.min()

np.int64(1)

In [ ]:
array.sum()

np.int64(45)

In [ ]:
# sum of array by column
np.sum(array ,axis=0)

array([12, 15, 18])

In [ ]:
# sum of array by row
np.sum(array ,axis=1)

array([ 6, 15, 24])

In [ ]:
array.mean()

np.float64(5.0)

In [ ]:
array.std()

np.float64(2.581988897471611)

In [ ]:
#index of that max number
array.argmax()

np.int64(8)

In [ ]:
#index of that min number
array.argmin()

np.int64(0)

In [ ]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arra=np.arange(1,31).reshape(6,5)
arra

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arra[4]

array([21, 22, 23, 24, 25])

In [ ]:
arra[1:5]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arra[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [ ]:
arra

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arra[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
#first this is row and second is column
arra[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [ ]:
  #boolen indexing
even_number=np.arange(1,15)
even_number

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
bool_even=even_number%2==0
bool_even

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True])

In [ ]:
even_number=even_number[bool_even]
even_number

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
##arithmatic opertaion
a1=np.array([1,2,3,4,5,6,7,8,9])
a2=np.array([10,11,12,13,14,15,16,17,18])


In [ ]:
a1+a2

array([11, 13, 15, 17, 19, 21, 23, 25, 27])

In [ ]:
a2-a1

array([9, 9, 9, 9, 9, 9, 9, 9, 9])

In [ ]:
a2*a1

array([ 10,  22,  36,  52,  70,  90, 112, 136, 162])

In [ ]:
a2/a1

array([10.        ,  5.5       ,  4.        ,  3.25      ,  2.8       ,
        2.5       ,  2.28571429,  2.125     ,  2.        ])

In [ ]:
a2//a1

array([10,  5,  4,  3,  2,  2,  2,  2,  2])

In [ ]:
a2**a1

array([          10,          121,         1728,        28561,
             537824,     11390625,    268435456,   6975757441,
       198359290368])

In [ ]:
a=np.array([[12,1],[2,4]])
b=np.array([[2,3],[4,2]])

In [ ]:
a @ b

array([[28, 38],
       [20, 14]])

In [ ]:
np.dot(a,b)

array([[28, 38],
       [20, 14]])

In [ ]:
#data transpose in row converted in column nd column converted into  row
a.T

array([[12,  2],
       [ 1,  4]])

In [ ]:
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
np.vstack((A,B))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.hstack((A,B))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.column_stack((A,B))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [ ]:
c=np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.hsplit(c,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [ ]:
np.vsplit(c,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]