<a href="https://colab.research.google.com/github/DipaliDhonnar/python/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
b=np.sum(s,axis=1)
for i in b:
   if i !=45:
     print("sudo is not valid")
else:
   print("sudo is valid for row")


sudo is valid for row


In [ ]:
c=np.sum(s,axis=1)
for i in b:
   if i !=45:
     print("sudo is not valid")
else:
   print("sudo is valid for row")


sudo is valid for row


In [ ]:
for i in range(0,9,3):
   for j in range(0,9,3):
      a=np.sum(s[i:i+3,j:j+3])
      if a!=45:
        print("sudo is not valid")
else:
   print("sudo is valid for trinagle")

sudo is valid for trinagle


In [ ]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [ ]:
#average age
np.mean(data[:,0])

np.float64(18.4)

In [ ]:
#extract all math marks
data[:,1]

array([85, 92, 76, 65, 90])

In [ ]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [ ]:
#Get details of the student who scored more than 90 in Math.
data_bool=data[:,1]>90
print(data_bool)
data[data_bool]

[False  True False False False]


array([[19, 92, 88]])

In [ ]:
#Increase Math marks of all students by 5.
data[:,1]+5

array([90, 97, 81, 70, 95])

In [ ]:
#Find how many students are younger than 19.
data_bool=data[:,0]>=19
print(data_bool)
len(data[data_bool])

[False  True False False  True]


2

In [ ]:
#Calculate the average marks in each subject (column-wise mean).
print(data)
math_avg=np.mean(data[:,1])
print(f"math average is {math_avg}")
scie_avg=np.mean(data[:,2])
print(f"science average is {scie_avg}")

[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65 70]
 [20 90 85]]
math average is 81.6
science average is 83.2


In [ ]:
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [ ]:
#Get data of students who scored at least 80 in both subjects.
math_over_80 = data[:,1] >= 80
science_over_80 = data[:,2] >= 80
students_both_over_80 = data[math_over_80 & science_over_80]
print(students_both_over_80)

[[19 92 88]
 [20 90 85]]


In [ ]:
#Replace all Science marks < 75 with 0.
print(data)
data[:,2][data[:,2]<75]=0
data


[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65 70]
 [20 90 85]]


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])